#!/bin/sh

# Copyright (C) 2001-2009 Karsten Reincke <karsten.reincke@fodina.de >
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# file <prj.spec> version <#3.2.0#> of project <GTGT>

IGNF=.gitignore

if [ ! -f Makefile ];
then
  ./reconf
  ./configure
fi
make distclean

DELCONF_FILES=`ls config.*`
DELETE_FILES=" config.cache  ltmain.sh  acconfig.h    Makefile    Makefile.in    aclocal.m4    configure    ${DELCONF_FILES}"
for DF in ${DELETE_FILES};
do
  echo "deleting ${DF}"
  find . -name ${DF} -exec rm \{\} \;
done

find . -type l -exec rm \{\} \;

find . -type d |  grep -v "CVS" | grep -v ".svn" | while read DIR; do

if [ "$DIR" = "./autom4te.cache" ];
then
  echo "deleting $DIR"
  rm -r $DIR
  continue
fi

if [ "$DIR" = "." ];
then
  continue
fi

echo "<$DIR>"
(
  cd $DIR
  pwd
  echo "Makefile.in" > ${IGNF}
  echo "Makefile" >> ${IGNF}
  echo "*.la" >> ${IGNF}
  echo "*.lo" >> ${IGNF}
  echo "*.o" >> ${IGNF}
  echo ".libs" >> ${IGNF}
  echo ".deps" >> ${IGNF}

  if [ -e .svn ];
  then
    svn propset svn:ignore -F ${IGNF} .;
  fi
)

done

echo "COPYING" > ${IGNF}
echo "INSTALL" >> ${IGNF}
echo "config.guess" >> ${IGNF}
echo "config.sub" >> ${IGNF}
echo "install-sh" >> ${IGNF}
echo "ltmain.sh" >> ${IGNF}
echo "ltconfig" >> ${IGNF}
echo "missing" >> ${IGNF}
echo "mkinstalldirs" >> ${IGNF}
echo "aclocal.m4" >> ${IGNF}
echo "configure" >> ${IGNF}
echo "Makefile.in" >> ${IGNF}
echo "Makefile" >> ${IGNF} 
echo "stamp-h" >> ${IGNF}
echo "config.h" >> ${IGNF}
echo "config.log" >> ${IGNF}
echo "config.status" >> ${IGNF}
echo "libtool" >> ${IGNF}

if [ -e .svn ];
then
  svn propset svn:ignore -F ${IGNF} .;
fi
