#!/bin/sh
#
# Copyright (C) 2001/2002/2003 karsten reincke <karsten.reincke@fodina.de>
#  
# This file is part of of the software-project GTGT.
# 
# GTGT is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# GTGT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# file <reconf> version <#3.2.0#> of project <GTGT>


TESTDIRS="/usr/local/gnu/share/aclocal /usr/local/share/aclocal /opt/gnome/share/aclocal /usr/share/aclocal /opt/share/aclocal"

 ACLOCAL_PATH="";
for dir in ${TESTDIRS};
do
   if [ -d ${dir} ];
   then
     ACLOCAL_PATH="-I ${dir} ${ACLOCAL_PATH}"
   fi
done

DELCONF_FILES=`ls config.*`
DELETE_FILES=" config.cache    acconfig.h    Makefile    Makefile.in    aclocal.m4    configure    ${DELCONF_FILES}"
for DF in ${DELETE_FILES}; 
do
  echo "deleting ${DF}"
  find . -name ${DF} -exec rm \{\} \;
done

find . -type l -exec rm \{\} \;

echo "- libtoolize"
libtoolize

echo "- aclocal."
aclocal $ACLOCAL_PATH 
echo "- autoconf."
autoconf
echo "- autoheader."
autoheader
echo "- automake."
automake -a
exit

