#!/bin/sh
#
# Copyright (C) 2020 Karsten Reincke, Deutsche Telekom AG
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#


TESTDIRS="/usr/local/gnu/share/aclocal /usr/local/share/aclocal /opt/gnome/share/aclocal /usr/share/aclocal /opt/share/aclocal"

 ACLOCAL_PATH="";
for dir in ${TESTDIRS};
do
   if [ -d ${dir} ];
   then
     ACLOCAL_PATH="-I ${dir} ${ACLOCAL_PATH}"
   fi
done

DELCONF_FILES=`ls config.*`
DELETE_FILES=" config.cache    acconfig.h    Makefile    Makefile.in    aclocal.m4    configure    ${DELCONF_FILES}"
for DF in ${DELETE_FILES};
do
  echo "deleting ${DF}"
  find . -name ${DF} -exec rm \{\} \;
done

find . -type l -exec rm \{\} \;

echo "- libtoolize"
libtoolize

echo "- aclocal."
aclocal $ACLOCAL_PATH
echo "- autoconf."
autoconf
echo "- autoheader."
autoheader
echo "- automake."
automake -a
exit
